<?php

$email1 =
    '<!DOCTYPE html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width"/>
        <style>
        body{
        width:50% !important;
        min-width: 0%;
        max-width: 50;
      -webkit-text-size-adjust:50%;
      -ms-text-size-adjust:50%;
      margin:0;
      padding:0;
    }
    h1 {
        font-family: Trebuchet MS;
        color: Red;
        font-size: 23px;
    }
    h2 {
        font-family: Trebuchet MS;
        color: black;
        font-size: 13px;
    }

    h3 {
        font-family: Trebuchet MS;
        color: #000000;
        font-size: 10px;
    }
      h4 {
        font-family: Trebuchet MS;
        color: #0000ff;
        font-size: 10px;
        max-width: 15;
    }

        </style>
    <title>PFI MonitorEmail</title>
    </head>
    <body>
    <h1>PFI Alert Test</h1>
    <h2>
    Transaction Count Alert:
    </h2>
    <h3>
    No Successful PFI transactions seen in last 45 minutes.
    Please check on boron for latest traffic using:
    </h3>
    <h4>
    SELECT  top 100
		pfi.id,
		pfi.msisdn,
		stat1.Description as 2Flow Type",
		stat2.Description as "Transaction Status",
		stat3.Description as "MNO",
		pfi.created,
		pfi.charged,
		pfi.receiptsent,
		pfi.merchanttransactionref,
		pfi.esccontenturl,
		pfi.ESCMerchantUrlId,
		pfi.Amount,
		pfi.ProductId
  FROM [PayForIt].[dbo].[Transaction] pfi
  full outer join [PayForIt].[dbo].[PaymentFlow] stat1 on pfi.paymentflowid = stat1.id
  full outer join [PayForIt].[dbo].[TransactionStatus] stat2 on pfi.transactionstatusid = stat2.id
  full outer join [PayForIt].[dbo].[Network] stat3 on pfi.networkid = stat3.id
  where 1=1
  order by pfi.created desc
  </h4>

  <h3>
  Please also check PFI All applications on Titanium.winprod.lan are running without errors

  Further information can be found in handover as per : http://hw-ops01/WinWiki/PFI_V4

  Generated by PFI V4 Monitor: http://mh-pfi-mon-01.win.local:81/overview.php
 </h3>
    </body>
    </html>';



$email2 =
    '<!DOCTYPE html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width"/>
       <style>
        body{
        width:50% !important;
        min-width: 0%;
        max-width: 50;
      -webkit-text-size-adjust:50%;
      -ms-text-size-adjust:50%;
      margin:0;
      padding:0;
    }
    h1 {
        font-family: Trebuchet MS;
        color: Red;
        font-size: 23px;
    }
    h2 {
        font-family: Trebuchet MS;
        color: black;
        font-size: 13px;
    }

    h3 {
        font-family: Trebuchet MS;
        color: #000000;
        font-size: 10px;
    }
      h4 {
        font-family: Trebuchet MS;
        color: #0000ff;
        font-size: 10px;
    }

        </style>
    <title>PFI MonitorEmail</title>
    </head>
    <body>
    <h1>PFI Alert Test</h1>
    <h2>
    Transaction Count Alert:
    </h2>
    <h3>
    No Successful PFI transactions seen in last 45 minutes.
    Please check on boron for latest traffic using:
    </h3>
    <h4>
    SELECT  top 100
		pfi.id,
		pfi.msisdn,
		stat1.Description as 2Flow Type",
		stat2.Description as "Transaction Status",
		stat3.Description as "MNO",
		pfi.created,
		pfi.charged,
		pfi.receiptsent,
		pfi.merchanttransactionref,
		pfi.esccontenturl,
		pfi.ESCMerchantUrlId,
		pfi.Amount,
		pfi.ProductId
  FROM [PayForIt].[dbo].[Transaction] pfi
  full outer join [PayForIt].[dbo].[PaymentFlow] stat1 on pfi.paymentflowid = stat1.id
  full outer join [PayForIt].[dbo].[TransactionStatus] stat2 on pfi.transactionstatusid = stat2.id
  full outer join [PayForIt].[dbo].[Network] stat3 on pfi.networkid = stat3.id
  where 1=1
  order by pfi.created desc
  </h4>

  <h3>
  Please also check PFI All applications on Titanium.winprod.lan are running without errors

  Further information can be found in handover as per : http://hw-ops01/WinWiki/PFI_V4

  Generated by PFI V4 Monitor: http://mh-pfi-mon-01.win.local:81/overview.php
 </h3>
    </body>
    </html>';


$email3 =
    '<!DOCTYPE html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width"/>
         <style>
        body{
        width:50% !important;
        min-width: 0%;
        max-width: 50;
      -webkit-text-size-adjust:50%;
      -ms-text-size-adjust:50%;
      margin:0;
      padding:0;
    }
    h1 {
        font-family: Trebuchet MS;
        color: Red;
        font-size: 23px;
    }
    h2 {
        font-family: Trebuchet MS;
        color: black;
        font-size: 13px;
    }

    h3 {
        font-family: Trebuchet MS;
        color: #000000;
        font-size: 10px;
    }
      h4 {
        font-family: Trebuchet MS;
        color: #0000ff;
        font-size: 10px;
    }

        </style>
    <title>PFI MonitorEmail</title>
    </head>
    <body>
    <h1>PFI Alert Test</h1>
    <h2>
    Transaction Count Alert:
    </h2>
    <h3>
    No Successful PFI transactions seen in last 45 minutes.
    Please check on boron for latest traffic using:
    </h3>
    <h4>
    SELECT  top 100
		pfi.id,
		pfi.msisdn,
		stat1.Description as 2Flow Type",
		stat2.Description as "Transaction Status",
		stat3.Description as "MNO",
		pfi.created,
		pfi.charged,
		pfi.receiptsent,
		pfi.merchanttransactionref,
		pfi.esccontenturl,
		pfi.ESCMerchantUrlId,
		pfi.Amount,
		pfi.ProductId
  FROM [PayForIt].[dbo].[Transaction] pfi
  full outer join [PayForIt].[dbo].[PaymentFlow] stat1 on pfi.paymentflowid = stat1.id
  full outer join [PayForIt].[dbo].[TransactionStatus] stat2 on pfi.transactionstatusid = stat2.id
  full outer join [PayForIt].[dbo].[Network] stat3 on pfi.networkid = stat3.id
  where 1=1
  order by pfi.created desc
  </h4>

  <h3>
  Please also check PFI All applications on Titanium.winprod.lan are running without errors

  Further information can be found in handover as per : http://hw-ops01/WinWiki/PFI_V4

  Generated by PFI V4 Monitor: http://mh-pfi-mon-01.win.local:81/overview.php
 </h3>
    </body>
    </html>';

$email4 =
    '<!DOCTYPE html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width"/>
        <style>
        body{
        width:50% !important;
        min-width: 0%;
        max-width: 50;
      -webkit-text-size-adjust:50%;
      -ms-text-size-adjust:50%;
      margin:0;
      padding:0;
    }
    h1 {
        font-family: Trebuchet MS;
        color: Red;
        font-size: 23px;
    }
    h2 {
        font-family: Trebuchet MS;
        color: black;
        font-size: 13px;
    }

    h3 {
        font-family: Trebuchet MS;
        color: #000000;
        font-size: 10px;
    }
      h4 {
        font-family: Trebuchet MS;
        color: #0000ff;
        font-size: 10px;
    }

        </style>
    <title>PFI MonitorEmail</title>
    </head>
   <body>
    <h1>PFI Alert Test</h1>
    <h2>
    Transaction Count Alert:
    </h2>
    <h3>
    No Successful PFI transactions seen in last 45 minutes.
    Please check on boron for latest traffic using:
    </h3>
    <h4>
    SELECT  top 100
		pfi.id,
		pfi.msisdn,
		stat1.Description as 2Flow Type",
		stat2.Description as "Transaction Status",
		stat3.Description as "MNO",
		pfi.created,
		pfi.charged,
		pfi.receiptsent,
		pfi.merchanttransactionref,
		pfi.esccontenturl,
		pfi.ESCMerchantUrlId,
		pfi.Amount,
		pfi.ProductId
  FROM [PayForIt].[dbo].[Transaction] pfi
  full outer join [PayForIt].[dbo].[PaymentFlow] stat1 on pfi.paymentflowid = stat1.id
  full outer join [PayForIt].[dbo].[TransactionStatus] stat2 on pfi.transactionstatusid = stat2.id
  full outer join [PayForIt].[dbo].[Network] stat3 on pfi.networkid = stat3.id
  where 1=1
  order by pfi.created desc
  </h4>

  <h3>
  Please also check PFI All applications on Titanium.winprod.lan are running without errors

  Further information can be found in handover as per : http://hw-ops01/WinWiki/PFI_V4

  Generated by PFI V4 Monitor: http://mh-pfi-mon-01.win.local:81/overview.php
 </h3>
    </body>
    </html>';

?>