var query1 = 'SELECT count(*) FROM [PayForIt].[dbo].[Transaction] where TransactionStatusId = '6' and created  between dateadd(MINUTE,-10,getdate()) and getdate();'
var query2 = 'SELECT count(*) FROM [PayForIt].[dbo].[Transaction] where TransactionStatusId = '4' and created  between dateadd(MINUTE,-10,getdate()) and getdate();'
var query3 = 'SELECT count(*) FROM [PayForIt].[dbo].[Transaction] where TransactionStatusId = '7' and created  between dateadd(MINUTE,-10,getdate()) and getdate();'
var query4 =
var query5 =
var query6 =
var query7 =
